name: CI
on: [push, pull_request]

jobs:
  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Install Ganache-CLI
        run: npm install ganache-cli

      - name: Simple Client
        working-directory: simple-client
        env:
          MNEMONIC: pistol kiwi shrug future ozone ostrich match remove crucial oblige cream critic
        run: |
          npx ganache-cli -b 5 -a 2 -m "$MNEMONIC" &
          GANACHE_PID=$!
          sleep 5
          go run .
          kill $GANACHE_PID

      - name: Collateralized Channels
        working-directory: collateralized-channels
        env:
          GANACHE_CMD: npx ganache-cli
        run: go test -v -timeout 60s .

      - name: App Channel
        working-directory: app-channel
        env:
          GANACHE_CMD: npx ganache-cli
        run: go test -v -timeout 60s .
