name: CI
on: [push, pull_request]

jobs:
  test-examples:
    name: Test Examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Ganache-CLI
        run: npm install ganache-cli

      - name: Simple Client
        working-directory: simple-client
        env:
          MNEMONIC: pistol kiwi shrug future ozone ostrich match remove crucial oblige cream critic
        run: |
          npx ganache-cli -b 5 -a 2 -m "$MNEMONIC" &
          GANACHE_PID=$!
          sleep 5
          go run .
          kill $GANACHE_PID

      - name: Payment Channel
        working-directory: payment-channel
        env:
          KEY_DEPLOYER: '0x79ea8f62d97bc0591a4224c1725fca6b00de5b2cea286fe2e0bb35c5e76be46e'
          KEY_ALICE: '0x1af2e950272dd403de7a5760d41c6e44d92b6d02797e51810795ff03cc2cda4f'
          KEY_BOB: '0xf63d7d8e930bccd74e93cf5662fde2c28fd8be95edb70c73f1bdd863d07f412e'
          BALANCE: '10000000000000000000'
        run: |
          npx ganache-cli --account $KEY_DEPLOYER,$BALANCE --account $KEY_ALICE,$BALANCE --account $KEY_BOB,$BALANCE --blockTime=5 --gasPrice=0 &
          GANACHE_PID=$!
          sleep 3
          go run .
          kill $GANACHE_PID

      - name: Collateralized Channels
        working-directory: collateralized-channels
        env:
          GANACHE_CMD: npx ganache-cli
        run: go test -v -timeout 60s .

      - name: App Channel
        working-directory: app-channel
        env:
          GANACHE_CMD: npx ganache-cli
        run: go test -v -timeout 60s .
