name: CI

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Dependencies
      run: |
        docker pull trufflesuite/ganache-cli

    - name: Simple Client
      run: |
        docker run --name=ganache --rm --net=host trufflesuite/ganache-cli -b 5 -a 2 -m "pistol kiwi shrug future ozone ostrich match remove crucial oblige cream critic" &
        sleep 5
        cd simple-client && go run . && cd ..
        docker stop ganache

